name: Block Cloning
on: 
  pull_request:
  push:
jobs:
  block_clone:
    runs-on: ubuntu-latest
    steps:
      - name: Block unauthorized clones
        run: |
          echo "Warning: Cloning this repository is not allowed."
          exit 1
